run_name: analyse_distribution

env: walker
task: [walker_stand, walker_walk]
data_type: [medium, medium-replay]

mode: TxT # B (behavior policy), T (teacher policy)

seed: 1
device: cuda
discount: 0.99

# dataset
replay_buffer_dir_offline: ../../collect
replay_buffer_dir_online: ../../collect_pbrl
replay_buffer_size: 1200000
replay_buffer_num_workers: 4
batch_size: 1000000

bins: 3

hydra:
  run:
    dir: ./result_analyse_distribution/${run_name}-${now:%m-%d-%H-%M-%S}