defaults:
  - agent: pbrl
  - override hydra/launcher: submitit_local

# mode
# reward_free: false
# task settings
env: walker
task: walker_stand
data_type: medium-replay
agent_dir: ../../teacher_models/${env}/${task}/${data_type}
#obs_type: states             # [states, pixels]
#frame_stack: 3               # only works if obs_type=pixels
discount: 0.99
# amount to collect
num_collect_episodes: 1100

# pretrained
#snapshot_ts: 100000
#snapshot_base_dir: ./pretrained_models
# replay buffer
replay_buffer_size: 1100000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: false   # can be either true or false depending if we want to fine-tune encoder
# misc
seed: 1
device: cuda
save_video: true
use_tb: false
use_wandb: true
# experiment
experiment: exp


hydra:
  run:
    dir: ./collect_pbrl/${task}-${data_type}-${now:%m-%d-%H-%M-%S}
#    dir: ./collect/${task}-${agent.name}-medium-replay           # for collect_data_fixed, medium-replay
#    dir: ./collect/${task}-${agent.name}-expert                  # for collect_data_fixed, expert
#    dir: ./video/${task}-${agent.name}-video
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${task}-${data_type}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${task}-${data_type}/.slurm
