run_name: "walk_exp_stand_med"

env: walker
tasks: [walker_walk, walker_stand]
data_type: [expert, medium]

discount: 0.99
device: cuda
seed: 1

student_dir: ../../../student_models/${env}
hidden_dim: 256
lr: 1e-4
ensemble: 5

num_inference_episodes: 1000

hydra:
  run:
    dir: ./result_infer/online/${run_name}-${now:%m-%d-%H-%M-%S}