defaults:
  - agent: pbrl                                # td3_bc, cql, pbrl
  - override hydra/launcher: submitit_local

run_name: utds_single

# unsupervised exploration
# expl_agent: td3
# task settings
task: quadruped_run                               # main task to train (relable other datasets to this task)
share_task: [quadruped_run]                       # task for data sharing
data_type: [medium]                             # dataset for data sharing (corresponding each share_task)

hidden_dim: 256

discount: 0.99
# train settings
num_grad_steps: 1000000             #1M
log_every_steps: 10000               #1k
# eval
eval_every_steps: 10000             #10k
num_eval_episodes: 10               #10
# dataset
replay_buffer_dir: ../../collect    # make sure to update this if you change hydra run dir
replay_buffer_size: 10000000         # max: 10M
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
# misc
seed: 1
device: cuda
save_video: True
use_tb: False

# used for train_offline_single
data_main: expert

deterministic_actor: True

wandb: True
hydra:
  run:
#    dir: ./result_td3bc_share/${task}-Share_${share_task[0]}_${share_task[1]}-Data_${data_type[0]}_${data_type[1]}-${agent.name}-${now:%m-%d-%H-%M-%S}
#    dir: ./result_cql/${task}-${data_main}-${agent.name}-${now:%m-%d-%H-%M-%S}
#    dir: ./result_pbrl/${task}-${data_main}-${agent.name}-${now:%m-%d-%H-%M-%S}
    dir: ./result_utds_single/${run_name}-${now:%m-%d-%H-%M-%S}
#    dir: ./output/${task}-${data_main}-${agent.name}-${now:%m-%d-%H-%M-%S}

